const categories = [
  [
    {
      Abbreviation: "apa",
      value: 1,
      Description: "apartments / housing for rent",
      label: "H",
    },
    {
      Abbreviation: "hou",
      value: 2,
      Description: "wanted: apts",
      label: "H",
    },
    {
      Abbreviation: "com",
      value: 3,
      Description: "general community",
      label: "C",
    },
    {
      Abbreviation: "biz",
      value: 4,
      Description: "small biz ads",
      label: "B",
    },
    {
      Abbreviation: "for",
      value: 5,
      Description: "general for sale - by owner",
      label: "S",
    },
    {
      Abbreviation: "sys",
      value: 7,
      Description: "computers - by owner",
      label: "S",
    },
    { Abbreviation: "eve", value: 8, Description: "events", label: "E" },
    {
      Abbreviation: "res",
      value: 10,
      Description: "resumes / job wanted",
      label: "R",
    },
    {
      Abbreviation: "web",
      value: 11,
      Description: "web/html/info design",
      label: "J",
    },
    {
      Abbreviation: "bus",
      value: 12,
      Description: "business/mgmt",
      label: "J",
    },
    {
      Abbreviation: "mar",
      value: 13,
      Description: "marketing/advertising/pr",
      label: "J",
    },
    {
      Abbreviation: "etc",
      value: 15,
      Description: "et cetera",
      label: "J",
    },
    {
      Abbreviation: "wri",
      value: 16,
      Description: "writing/editing",
      label: "J",
    },
    {
      Abbreviation: "roo",
      value: 18,
      Description: "rooms & shares",
      label: "H",
    },
    {
      Abbreviation: "sha",
      value: 19,
      Description: "wanted: room/share",
      label: "H",
    },
    {
      Abbreviation: "wan",
      value: 20,
      Description: "wanted - by owner",
      label: "S",
    },
    {
      Abbreviation: "sof",
      value: 21,
      Description: "software/qa/dba/etc",
      label: "J",
    },
    {
      Abbreviation: "acc",
      value: 23,
      Description: "accounting/finance",
      label: "J",
    },
    {
      Abbreviation: "ofc",
      value: 24,
      Description: "admin/office",
      label: "J",
    },
    {
      Abbreviation: "med",
      value: 25,
      Description: "art/media/design",
      label: "J",
    },
    {
      Abbreviation: "hea",
      value: 26,
      Description: "healthcare",
      label: "J",
    },
    {
      Abbreviation: "ret",
      value: 27,
      Description: "retail/wholesale",
      label: "J",
    },
    {
      Abbreviation: "npo",
      value: 28,
      Description: "nonprofit",
      label: "J",
    },
    {
      Abbreviation: "vol",
      value: 29,
      Description: "volunteers",
      label: "C",
    },
    {
      Abbreviation: "act",
      value: 35,
      Description: "activity partners",
      label: "C",
    },
    {
      Abbreviation: "rid",
      value: 36,
      Description: "rideshare",
      label: "C",
    },
    { Abbreviation: "pet", value: 37, Description: "pets", label: "C" },
    { Abbreviation: "cls", value: 38, Description: "classes", label: "E" },
    {
      Abbreviation: "sub",
      value: 39,
      Description: "sublets & temporary",
      label: "H",
    },
    {
      Abbreviation: "off",
      value: 40,
      Description: "office & commercial",
      label: "H",
    },
    {
      Abbreviation: "prk",
      value: 41,
      Description: "parking & storage",
      label: "H",
    },
    { Abbreviation: "bar", value: 42, Description: "barter", label: "S" },
    {
      Abbreviation: "tix",
      value: 44,
      Description: "tickets - by owner",
      label: "S",
    },
    {
      Abbreviation: "lgl",
      value: 47,
      Description: "legal/paralegal",
      label: "J",
    },
    {
      Abbreviation: "egr",
      value: 48,
      Description: "architect/engineer/cad",
      label: "J",
    },
    { Abbreviation: "sls", value: 49, Description: "sales", label: "J" },
    {
      Abbreviation: "sad",
      value: 50,
      Description: "systems/networking",
      label: "J",
    },
    {
      Abbreviation: "tfr",
      value: 52,
      Description: "tv/film/video/radio",
      label: "J",
    },
    {
      Abbreviation: "hum",
      value: 54,
      Description: "human resource",
      label: "J",
    },
    {
      Abbreviation: "tch",
      value: 55,
      Description: "technical support",
      label: "J",
    },
    {
      Abbreviation: "kid",
      value: 56,
      Description: "childcare",
      label: "C",
    },
    {
      Abbreviation: "edu",
      value: 57,
      Description: "education/teaching",
      label: "J",
    },
    {
      Abbreviation: "sbw",
      value: 58,
      Description: "wanted: sublet/temp",
      label: "H",
    },
    {
      Abbreviation: "trd",
      value: 59,
      Description: "skilled trades/artisan",
      label: "J",
    },
    {
      Abbreviation: "fee",
      value: 60,
      Description: "apts broker fee",
      label: "H",
    },
    {
      Abbreviation: "gov",
      value: 61,
      Description: "government",
      label: "J",
    },
    {
      Abbreviation: "mis",
      value: 63,
      Description: "missed connections",
      label: "C",
    },
    {
      Abbreviation: "swp",
      value: 65,
      Description: "housing swap",
      label: "H",
    },
    {
      Abbreviation: "cal",
      value: 66,
      Description: "event calendar",
      label: "L",
    },
    {
      Abbreviation: "bik",
      value: 68,
      Description: "bicycles - by owner",
      label: "S",
    },
    {
      Abbreviation: "mcy",
      value: 69,
      Description: "motorcycles/scooters - by owner",
      label: "S",
    },
    { Abbreviation: "ats", value: 70, Description: "artists", label: "C" },
    {
      Abbreviation: "muc",
      value: 71,
      Description: "musicians",
      label: "C",
    },
    {
      Abbreviation: "gms",
      value: 73,
      Description: "garage & moving sales",
      label: "S",
    },
    {
      Abbreviation: "sci",
      value: 75,
      Description: "science/biotech",
      label: "J",
    },
    {
      Abbreviation: "cps",
      value: 76,
      Description: "computer services",
      label: "B",
    },
    {
      Abbreviation: "crs",
      value: 77,
      Description: "creative services",
      label: "B",
    },
    {
      Abbreviation: "evs",
      value: 79,
      Description: "event services",
      label: "B",
    },
    {
      Abbreviation: "hss",
      value: 80,
      Description: "household services",
      label: "B",
    },
    {
      Abbreviation: "lss",
      value: 81,
      Description: "lessons & tutoring",
      label: "B",
    },
    {
      Abbreviation: "lbs",
      value: 82,
      Description: "labor / hauling / moving",
      label: "B",
    },
    {
      Abbreviation: "sks",
      value: 83,
      Description: "skilled trade services",
      label: "B",
    },
    {
      Abbreviation: "nfb",
      value: 85,
      Description: "apts broker no fee",
      label: "H",
    },
    {
      Abbreviation: "abo",
      value: 86,
      Description: "apts by owner",
      label: "H",
    },
    { Abbreviation: "pol", value: 87, Description: "politics", label: "C" },
    {
      Abbreviation: "laf",
      value: 88,
      Description: "lost & found",
      label: "C",
    },
    {
      Abbreviation: "rnr",
      value: 90,
      Description: "rants & raves",
      label: "C",
    },
    { Abbreviation: "grp", value: 91, Description: "groups", label: "C" },
    {
      Abbreviation: "bks",
      value: 92,
      Description: "books & magazines - by owner",
      label: "S",
    },
    {
      Abbreviation: "spo",
      value: 93,
      Description: "sporting goods - by owner",
      label: "S",
    },
    {
      Abbreviation: "clo",
      value: 94,
      Description: "clothing & accessories - by owner",
      label: "S",
    },
    {
      Abbreviation: "clt",
      value: 95,
      Description: "collectibles - by owner",
      label: "S",
    },
    {
      Abbreviation: "ele",
      value: 96,
      Description: "electronics - by owner",
      label: "S",
    },
    {
      Abbreviation: "hsh",
      value: 97,
      Description: "household items - by owner",
      label: "S",
    },
    {
      Abbreviation: "msg",
      value: 98,
      Description: "musical instruments - by owner",
      label: "S",
    },
    {
      Abbreviation: "vac",
      value: 99,
      Description: "vacation rentals",
      label: "H",
    },
    {
      Abbreviation: "csr",
      value: 100,
      Description: "customer service",
      label: "J",
    },
    {
      Abbreviation: "zip",
      value: 101,
      Description: "free stuff",
      label: "S",
    },
    {
      Abbreviation: "lgs",
      value: 103,
      Description: "legal services",
      label: "B",
    },
    {
      Abbreviation: "fns",
      value: 104,
      Description: "financial services",
      label: "B",
    },
    {
      Abbreviation: "rts",
      value: 105,
      Description: "real estate services",
      label: "B",
    },
    {
      Abbreviation: "aos",
      value: 106,
      Description: "automotive services",
      label: "B",
    },
    {
      Abbreviation: "bab",
      value: 107,
      Description: "baby & kid stuff - by owner",
      label: "S",
    },
    {
      Abbreviation: "tlg",
      value: 108,
      Description: "talent gigs",
      label: "G",
    },
    {
      Abbreviation: "cwg",
      value: 109,
      Description: "crew gigs",
      label: "G",
    },
    {
      Abbreviation: "cpg",
      value: 110,
      Description: "computer gigs",
      label: "G",
    },
    {
      Abbreviation: "lbg",
      value: 111,
      Description: "labor gigs",
      label: "G",
    },
    {
      Abbreviation: "wrg",
      value: 112,
      Description: "writing gigs",
      label: "G",
    },
    {
      Abbreviation: "dmg",
      value: 113,
      Description: "domestic gigs",
      label: "G",
    },
    {
      Abbreviation: "crg",
      value: 114,
      Description: "creative gigs",
      label: "G",
    },
    {
      Abbreviation: "evg",
      value: 115,
      Description: "event gigs",
      label: "G",
    },
    {
      Abbreviation: "vnn",
      value: 116,
      Description: "local news and views",
      label: "C",
    },
    {
      Abbreviation: "emd",
      value: 117,
      Description: "cds / dvds / vhs - by owner",
      label: "S",
    },
    {
      Abbreviation: "tls",
      value: 118,
      Description: "tools - by owner",
      label: "S",
    },
    {
      Abbreviation: "boa",
      value: 119,
      Description: "boats - by owner",
      label: "S",
    },
    {
      Abbreviation: "jwl",
      value: 120,
      Description: "jewelry - by owner",
      label: "S",
    },
    {
      Abbreviation: "rew",
      value: 121,
      Description: "wanted: real estate",
      label: "H",
    },
    {
      Abbreviation: "pts",
      value: 122,
      Description: "auto parts - by owner",
      label: "S",
    },
    {
      Abbreviation: "rvs",
      value: 124,
      Description: "rvs - by owner",
      label: "S",
    },
    {
      Abbreviation: "trp",
      value: 125,
      Description: "transportation",
      label: "J",
    },
    {
      Abbreviation: "spa",
      value: 126,
      Description: "salon/spa/fitness",
      label: "J",
    },
    {
      Abbreviation: "rej",
      value: 127,
      Description: "real estate",
      label: "J",
    },
    {
      Abbreviation: "mnu",
      value: 128,
      Description: "manufacturing",
      label: "J",
    },
    {
      Abbreviation: "fbh",
      value: 129,
      Description: "food/beverage/hospitality",
      label: "J",
    },
    {
      Abbreviation: "lab",
      value: 130,
      Description: "general labor",
      label: "J",
    },
    {
      Abbreviation: "sec",
      value: 131,
      Description: "security",
      label: "J",
    },
    {
      Abbreviation: "tag",
      value: 132,
      Description: "toys & games - by owner",
      label: "S",
    },
    {
      Abbreviation: "grd",
      value: 133,
      Description: "farm & garden - by owner",
      label: "S",
    },
    {
      Abbreviation: "bfs",
      value: 134,
      Description: "business/commercial - by owner",
      label: "S",
    },
    {
      Abbreviation: "art",
      value: 135,
      Description: "arts & crafts - by owner",
      label: "S",
    },
    {
      Abbreviation: "mat",
      value: 136,
      Description: "materials - by owner",
      label: "S",
    },
    {
      Abbreviation: "pho",
      value: 137,
      Description: "photo/video - by owner",
      label: "S",
    },
    {
      Abbreviation: "bts",
      value: 138,
      Description: "beauty services",
      label: "B",
    },
    {
      Abbreviation: "wet",
      value: 139,
      Description: "writing / editing / translation",
      label: "B",
    },
    {
      Abbreviation: "trv",
      value: 140,
      Description: "travel/vacation services",
      label: "B",
    },
    {
      Abbreviation: "fuo",
      value: 141,
      Description: "furniture - by owner",
      label: "S",
    },
    {
      Abbreviation: "fud",
      value: 142,
      Description: "furniture - by dealer",
      label: "S",
    },
    {
      Abbreviation: "reo",
      value: 143,
      Description: "real estate - by owner",
      label: "H",
    },
    {
      Abbreviation: "reb",
      value: 144,
      Description: "real estate - by broker",
      label: "H",
    },
    {
      Abbreviation: "cto",
      value: 145,
      Description: "cars & trucks - by owner",
      label: "S",
    },
    {
      Abbreviation: "ctd",
      value: 146,
      Description: "cars & trucks - by dealer",
      label: "S",
    },
    {
      Abbreviation: "app",
      value: 149,
      Description: "appliances - by owner",
      label: "S",
    },
    {
      Abbreviation: "atq",
      value: 150,
      Description: "antiques - by owner",
      label: "S",
    },
    {
      Abbreviation: "vgm",
      value: 151,
      Description: "video gaming - by owner",
      label: "S",
    },
    {
      Abbreviation: "hab",
      value: 152,
      Description: "health and beauty - by owner",
      label: "S",
    },
    {
      Abbreviation: "mob",
      value: 153,
      Description: "cell phones - by owner",
      label: "S",
    },
    {
      Abbreviation: "fgs",
      value: 154,
      Description: "farm & garden services",
      label: "B",
    },
    {
      Abbreviation: "pas",
      value: 155,
      Description: "pet services",
      label: "B",
    },
    {
      Abbreviation: "mas",
      value: 156,
      Description: "marine services",
      label: "B",
    },
    {
      Abbreviation: "cys",
      value: 158,
      Description: "cycle services",
      label: "B",
    },
    {
      Abbreviation: "mcd",
      value: 160,
      Description: "motorcycles/scooters - by dealer",
      label: "S",
    },
    {
      Abbreviation: "tid",
      value: 161,
      Description: "tickets - by dealer",
      label: "S",
    },
    {
      Abbreviation: "ppd",
      value: 162,
      Description: "appliances - by dealer",
      label: "S",
    },
    {
      Abbreviation: "ptd",
      value: 163,
      Description: "auto parts - by dealer",
      label: "S",
    },
    {
      Abbreviation: "bod",
      value: 164,
      Description: "boats - by dealer",
      label: "S",
    },
    {
      Abbreviation: "mod",
      value: 165,
      Description: "cell phones - by dealer",
      label: "S",
    },
    {
      Abbreviation: "syd",
      value: 166,
      Description: "computers - by dealer",
      label: "S",
    },
    {
      Abbreviation: "eld",
      value: 167,
      Description: "electronics - by dealer",
      label: "S",
    },
    {
      Abbreviation: "rvd",
      value: 168,
      Description: "rvs - by dealer",
      label: "S",
    },
    {
      Abbreviation: "atd",
      value: 169,
      Description: "antiques - by dealer",
      label: "S",
    },
    {
      Abbreviation: "ard",
      value: 170,
      Description: "arts & crafts - by dealer",
      label: "S",
    },
    {
      Abbreviation: "bad",
      value: 171,
      Description: "baby & kid stuff - by dealer",
      label: "S",
    },
    {
      Abbreviation: "bid",
      value: 172,
      Description: "bicycles - by dealer",
      label: "S",
    },
    {
      Abbreviation: "bkd",
      value: 173,
      Description: "books & magazines - by dealer",
      label: "S",
    },
    {
      Abbreviation: "bfd",
      value: 174,
      Description: "business/commercial - by dealer",
      label: "S",
    },
    {
      Abbreviation: "emq",
      value: 175,
      Description: "cds / dvds / vhs - by dealer",
      label: "S",
    },
    {
      Abbreviation: "cld",
      value: 176,
      Description: "clothing & accessories - by dealer",
      label: "S",
    },
    {
      Abbreviation: "cbd",
      value: 177,
      Description: "collectibles - by dealer",
      label: "S",
    },
    {
      Abbreviation: "grq",
      value: 178,
      Description: "farm & garden - by dealer",
      label: "S",
    },
    {
      Abbreviation: "fod",
      value: 179,
      Description: "general for sale - by dealer",
      label: "S",
    },
    {
      Abbreviation: "had",
      value: 180,
      Description: "health and beauty - by dealer",
      label: "S",
    },
    {
      Abbreviation: "hsd",
      value: 181,
      Description: "household items - by dealer",
      label: "S",
    },
    {
      Abbreviation: "jwd",
      value: 182,
      Description: "jewelry - by dealer",
      label: "S",
    },
    {
      Abbreviation: "mad",
      value: 183,
      Description: "materials - by dealer",
      label: "S",
    },
    {
      Abbreviation: "msd",
      value: 184,
      Description: "musical instruments - by dealer",
      label: "S",
    },
    {
      Abbreviation: "phd",
      value: 185,
      Description: "photo/video - by dealer",
      label: "S",
    },
    {
      Abbreviation: "sgd",
      value: 186,
      Description: "sporting goods - by dealer",
      label: "S",
    },
    {
      Abbreviation: "tld",
      value: 187,
      Description: "tools - by dealer",
      label: "S",
    },
    {
      Abbreviation: "tad",
      value: 188,
      Description: "toys & games - by dealer",
      label: "S",
    },
    {
      Abbreviation: "vgd",
      value: 189,
      Description: "video gaming - by dealer",
      label: "S",
    },
    {
      Abbreviation: "wad",
      value: 190,
      Description: "wanted - by dealer",
      label: "S",
    },
    {
      Abbreviation: "snw",
      value: 191,
      Description: "atvs, utvs, snowmobiles - by owner",
      label: "S",
    },
    {
      Abbreviation: "snd",
      value: 192,
      Description: "atvs, utvs, snowmobiles - by dealer",
      label: "S",
    },
    {
      Abbreviation: "hvo",
      value: 193,
      Description: "heavy equipment - by owner",
      label: "S",
    },
    {
      Abbreviation: "hvd",
      value: 194,
      Description: "heavy equipment - by dealer",
      label: "S",
    },
    {
      Abbreviation: "mpo",
      value: 195,
      Description: "motorcycle parts - by owner",
      label: "S",
    },
    {
      Abbreviation: "mpd",
      value: 196,
      Description: "motorcycle parts - by dealer",
      label: "S",
    },
    {
      Abbreviation: "bop",
      value: 197,
      Description: "bicycle parts - by owner",
      label: "S",
    },
    {
      Abbreviation: "bdp",
      value: 198,
      Description: "bicycle parts - by dealer",
      label: "S",
    },
    {
      Abbreviation: "sop",
      value: 199,
      Description: "computer parts - by owner",
      label: "S",
    },
    {
      Abbreviation: "sdp",
      value: 200,
      Description: "computer parts - by dealer",
      label: "S",
    },
    {
      Abbreviation: "bpo",
      value: 201,
      Description: "boat parts - by owner",
      label: "S",
    },
    {
      Abbreviation: "bpd",
      value: 202,
      Description: "boat parts - by dealer",
      label: "S",
    },
    {
      Abbreviation: "wto",
      value: 203,
      Description: "auto wheels & tires - by owner",
      label: "S",
    },
    {
      Abbreviation: "wtd",
      value: 204,
      Description: "auto wheels & tires - by dealer",
      label: "S",
    },
    {
      Abbreviation: "tro",
      value: 205,
      Description: "trailers - by owner",
      label: "S",
    },
    {
      Abbreviation: "trb",
      value: 206,
      Description: "trailers - by dealer",
      label: "S",
    },
    {
      Abbreviation: "cms",
      value: 207,
      Description: "cell phone / mobile services",
      label: "B",
    },
    {
      Abbreviation: "avo",
      value: 208,
      Description: "aviation - by owner",
      label: "S",
    },
    {
      Abbreviation: "avd",
      value: 209,
      Description: "aviation - by dealer",
      label: "S",
    },
  ],
];

export default categories;
