export const cities = [
  "abilene, TX",
  "akron / canton",
  "albany, GA",
  "albany, NY",
  "albuquerque",
  "altoona-johnstown",
  "amarillo, TX",
  "ames, IA",
  "anchorage / mat-su",
  "annapolis, MD",
  "ann arbor, MI",
  "appleton-oshkosh-FDL",
  "asheville, NC",
  "ashtabula, OH",
  "athens, GA",
  "athens, OH",
  "atlanta, GA",
  "auburn, AL",
  "augusta, GA",
  "austin, TX",
  "bakersfield, CA",
  "baltimore, MD",
  "baton rouge",
  "battle creek, MI",
  "beaumont / port arthur",
  "bellingham, WA",
  "bemidji, MN",
  "bend, OR",
  "billings, MT",
  "binghamton, NY",
  "birmingham, AL",
  "bismarck, ND",
  "bloomington, IN",
  "bloomington-normal",
  "boise, ID",
  "boone, NC",
  "boston",
  "boulder, CO",
  "bowling green, KY",
  "bozeman, MT",
  "brainerd, MN",
  "brownsville, TX",
  "brunswick, GA",
  "buffalo, NY",
  "butte, MT",
  "cape cod / islands",
  "catskills",
  "cedar rapids, IA",
  "central louisiana",
  "central michigan",
  "central NJ",
  "champaign urbana",
  "charleston, SC",
  "charleston, WV",
  "charlotte, NC",
  "charlottesville, VA",
  "chattanooga, TN",
  "chautauqua, NY",
  "chicago",
  "chico, CA",
  "chillicothe, OH",
  "cincinnati, OH",
  "clarksville, TN",
  "cleveland, OH",
  "clovis / portales",
  "college station, TX",
  "colorado springs",
  "columbia / jeff city",
  "columbia, SC",
  "columbus, GA",
  "columbus, OH",
  "cookeville, TN",
  "corpus christi, TX",
  "corvallis/albany",
  "cumberland valley",
  "dallas / fort worth",
  "danville",
  "daytona beach",
  "dayton / springfield",
  "decatur, IL",
  "deep east texas",
  "delaware",
  "del rio / eagle pass",
  "denver, CO",
  "des moines, IA",
  "detroit metro",
  "dothan, AL",
  "dubuque",
  "duluth / superior",
  "eastern CO",
  "eastern CT",
  "eastern kentucky",
  "eastern montana",
  "eastern NC",
  "eastern panhandle",
  "eastern shore",
  "east idaho",
  "east oregon",
  "eau claire, WI",
  "elko, NV",
  "elmira-corning",
  "el paso, TX",
  "erie, PA",
  "eugene, OR",
  "evansville, IN",
  "fairbanks, AK",
  "fargo / moorhead",
  "farmington, NM",
  "fayetteville, AR",
  "fayetteville, NC",
  "finger lakes, NY",
  "flagstaff / sedona",
  "flint, MI",
  "florence / muscle shoals",
  "florence, SC",
  "florida keys",
  "fort collins / north CO",
  "fort dodge, IA",
  "fort smith, AR",
  "fort wayne, IN",
  "frederick, MD",
  "fredericksburg, VA",
  "fresno / madera",
  "ft myers / SW florida",
  "gadsden-anniston",
  "gainesville, FL",
  "galveston, TX",
  "glens falls, NY",
  "gold country",
  "grand forks",
  "grand island, NE",
  "grand rapids, MI",
  "great falls, MT",
  "green bay, WI",
  "greensboro, NC",
  "greenville / upstate",
  "gulfport / biloxi",
  "hanford-corcoran",
  "harrisburg, PA",
  "harrisonburg, VA",
  "hartford, CT",
  "hattiesburg, MS",
  "hawaii",
  "heartland florida",
  "helena, MT",
  "hickory / lenoir",
  "high rockies",
  "hilton head",
  "holland, MI",
  "houma, LA",
  "houston, TX",
  "hudson valley, NY",
  "humboldt county",
  "huntington-ashland",
  "huntsville / decatur",
  "imperial county",
  "indianapolis",
  "inland empire, CA",
  "iowa city, IA",
  "ithaca, NY",
  "jackson, MI",
  "jackson, MS",
  "jackson, TN",
  "jacksonville, FL",
  "jacksonville, NC",
  "janesville, WI",
  "jersey shore",
  "jonesboro, AR",
  "joplin, MO",
  "kalamazoo, MI",
  "kalispell, MT",
  "kansas city, MO",
  "kenai peninsula",
  "kennewick-pasco-richland",
  "kenosha-racine",
  "killeen / temple / ft hood",
  "kirksville, MO",
  "klamath falls, OR",
  "knoxville, TN",
  "kokomo, IN",
  "la crosse, WI",
  "lafayette, LA",
  "lafayette / west lafayette",
  "lake charles, LA",
  "lakeland, FL",
  "lake of the ozarks",
  "lancaster, PA",
  "lansing, MI",
  "laredo, TX",
  "la salle co",
  "las cruces, NM",
  "las vegas",
  "lawrence, KS",
  "lawton, OK",
  "lehigh valley",
  "lewiston / clarkston",
  "lexington, KY",
  "lima / findlay",
  "lincoln, NE",
  "little rock",
  "logan, UT",
  "long island, NY",
  "los angeles",
  "louisville, KY",
  "lubbock, TX",
  "lynchburg, VA",
  "macon / warner robins",
  "madison, WI",
  "maine",
  "manhattan, KS",
  "mankato, MN",
  "mansfield, OH",
  "mason city, IA",
  "mattoon-charleston",
  "mcallen / edinburg",
  "meadville, PA",
  "medford-ashland",
  "memphis, TN",
  "mendocino county",
  "merced, CA",
  "meridian, MS",
  "milwaukee, WI",
  "minneapolis / st paul",
  "missoula, MT",
  "mobile, AL",
  "modesto, CA",
  "mohave county",
  "monroe, LA",
  "monroe, MI",
  "monterey bay",
  "montgomery, AL",
  "morgantown, WV",
  "moses lake, WA",
  "muncie / anderson",
  "muskegon, MI",
  "myrtle beach, SC",
  "nashville, TN",
  "new hampshire",
  "new haven, CT",
  "new orleans",
  "new river valley",
  "new york city",
  "norfolk / hampton roads",
  "north central FL",
  "north dakota",
  "northeast SD",
  "northern michigan",
  "northern panhandle",
  "northern WI",
  "north jersey",
  "north mississippi",
  "north platte, NE",
  "northwest CT",
  "northwest GA",
  "northwest KS",
  "northwest OK",
  "ocala, FL",
  "odessa / midland",
  "ogden-clearfield",
  "okaloosa / walton",
  "oklahoma city",
  "olympic peninsula",
  "omaha / council bluffs",
  "oneonta, NY",
  "orange county, CA",
  "oregon coast",
  "orlando, FL",
  "outer banks",
  "owensboro, KY",
  "palm springs, CA",
  "panama city, FL",
  "parkersburg-marietta",
  "pensacola, FL",
  "peoria, IL",
  "philadelphia",
  "phoenix, AZ",
  "pierre / central SD",
  "pittsburgh, PA",
  "plattsburgh-adirondacks",
  "poconos",
  "port huron, MI",
  "portland, OR",
  "potsdam-canton-massena",
  "prescott, AZ",
  "provo / orem",
  "pueblo, CO",
  "pullman / moscow",
  "quad cities, IA/IL",
  "raleigh / durham / CH",
  "rapid city / west SD",
  "reading, PA",
  "redding, CA",
  "reno / tahoe",
  "rhode island",
  "richmond, IN",
  "richmond, VA",
  "roanoke, VA",
  "rochester, MN",
  "rochester, NY",
  "rockford, IL",
  "roseburg, OR",
  "roswell / carlsbad",
  "sacramento",
  "saginaw-midland-baycity",
  "salem, OR",
  "salina, KS",
  "salt lake city",
  "san angelo, TX",
  "san antonio",
  "san diego",
  "sandusky, OH",
  "san luis obispo",
  "san marcos, TX",
  "santa barbara",
  "santa fe / taos",
  "santa maria, CA",
  "sarasota-bradenton",
  "savannah / hinesville",
  "scottsbluff / panhandle",
  "scranton / wilkes-barre",
  "seattle-tacoma",
  "SF bay area",
  "sheboygan, WI",
  "show low, AZ",
  "shreveport, LA",
  "sierra vista, AZ",
  "sioux city, IA",
  "sioux falls / SE SD",
  "siskiyou county",
  "skagit / island / SJI",
  "south bend / michiana",
  "south coast, MA",
  "south dakota",
  "southeast alaska",
  "southeast IA",
  "southeast KS",
  "southeast missouri",
  "southern illinois",
  "southern maryland",
  "southern WV",
  "south florida",
  "south jersey",
  "southwest KS",
  "southwest michigan",
  "southwest MN",
  "southwest MS",
  "southwest TX",
  "southwest VA",
  "space coast, FL",
  "spokane / coeur d'alene",
  "springfield, IL",
  "springfield, MO",
  "state college, PA",
  "statesboro, GA",
  "st augustine, FL",
  "st cloud, MN",
  "st george, UT",
  "stillwater, OK",
  "st joseph",
  "st louis, MO",
  "stockton, CA",
  "susanville, CA",
  "syracuse, NY",
  "tallahassee",
  "tampa bay area",
  "terre haute, IN",
  "texarkana",
  "texoma",
  "the thumb, MI",
  "toledo, OH",
  "topeka, KS",
  "treasure coast, FL",
  "tri-cities, TN",
  "tucson, AZ",
  "tulsa, OK",
  "tuscaloosa",
  "tuscarawas co",
  "twin falls, ID",
  "twin tiers NY/PA",
  "tyler / east TX",
  "upper peninsula, MI",
  "utica-rome-oneida",
  "valdosta, GA",
  "ventura county",
  "vermont",
  "victoria, TX",
  "visalia-tulare",
  "waco, TX",
  "washington, DC",
  "waterloo / cedar falls",
  "watertown, NY",
  "wausau, WI",
  "wenatchee, WA",
  "western IL",
  "western KY",
  "western maryland",
  "western massachusetts",
  "western slope",
  "west virginia (old)",
  "wichita falls, TX",
  "wichita, KS",
  "williamsport, PA",
  "wilmington, NC",
  "winchester, VA",
  "winston-salem, NC",
  "worcester / central MA",
  "wyoming",
  "yakima, WA",
  "york, PA",
  "youngstown, OH",
  "yuba-sutter, CA",
  "yuma, AZ",
  "zanesville / cambridge",
];
