export const cities = [
  { value: 0, label: "abilene, TX" },
  { value: 1, label: "akron / canton" },
  { value: 2, label: "albany, GA" },
  { value: 3, label: "albany, NY" },
  { value: 4, label: "albuquerque" },
  { value: 5, label: "altoona-johnstown" },
  { value: 6, label: "amarillo, TX" },
  { value: 7, label: "ames, IA" },
  { value: 8, label: "anchorage / mat-su" },
  { value: 9, label: "annapolis, MD" },
  { value: 10, label: "ann arbor, MI" },
  { value: 11, label: "appleton-oshkosh-FDL" },
  { value: 12, label: "asheville, NC" },
  { value: 13, label: "ashtabula, OH" },
  { value: 14, label: "athens, GA" },
  { value: 15, label: "athens, OH" },
  { value: 16, label: "atlanta, GA" },
  { value: 17, label: "auburn, AL" },
  { value: 18, label: "augusta, GA" },
  { value: 19, label: "austin, TX" },
  { value: 20, label: "bakersfield, CA" },
  { value: 21, label: "baltimore, MD" },
  { value: 22, label: "baton rouge" },
  { value: 23, label: "battle creek, MI" },
  { value: 24, label: "beaumont / port arthur" },
  { value: 25, label: "bellingham, WA" },
  { value: 26, label: "bemidji, MN" },
  { value: 27, label: "bend, OR" },
  { value: 28, label: "billings, MT" },
  { value: 29, label: "binghamton, NY" },
  { value: 30, label: "birmingham, AL" },
  { value: 31, label: "bismarck, ND" },
  { value: 32, label: "bloomington, IN" },
  { value: 33, label: "bloomington-normal" },
  { value: 34, label: "boise, ID" },
  { value: 35, label: "boone, NC" },
  { value: 36, label: "boston" },
  { value: 37, label: "boulder, CO" },
  { value: 38, label: "bowling green, KY" },
  { value: 39, label: "bozeman, MT" },
  { value: 40, label: "brainerd, MN" },
  { value: 41, label: "brownsville, TX" },
  { value: 42, label: "brunswick, GA" },
  { value: 43, label: "buffalo, NY" },
  { value: 44, label: "butte, MT" },
  { value: 45, label: "cape cod / islands" },
  { value: 46, label: "catskills" },
  { value: 47, label: "cedar rapids, IA" },
  { value: 48, label: "central louisiana" },
  { value: 49, label: "central michigan" },
  { value: 50, label: "central NJ" },
  { value: 51, label: "champaign urbana" },
  { value: 52, label: "charleston, SC" },
  { value: 53, label: "charleston, WV" },
  { value: 54, label: "charlotte, NC" },
  { value: 55, label: "charlottesville, VA" },
  { value: 56, label: "chattanooga, TN" },
  { value: 57, label: "chautauqua, NY" },
  { value: 58, label: "chicago" },
  { value: 59, label: "chico, CA" },
  { value: 60, label: "chillicothe, OH" },
  { value: 61, label: "cincinnati, OH" },
  { value: 62, label: "clarksville, TN" },
  { value: 63, label: "cleveland, OH" },
  { value: 64, label: "clovis / portales" },
  { value: 65, label: "college station, TX" },
  { value: 66, label: "colorado springs" },
  { value: 67, label: "columbia / jeff city" },
  { value: 68, label: "columbia, SC" },
  { value: 69, label: "columbus, GA" },
  { value: 70, label: "columbus, OH" },
  { value: 71, label: "cookeville, TN" },
  { value: 72, label: "corpus christi, TX" },
  { value: 73, label: "corvallis/albany" },
  { value: 74, label: "cumberland valley" },
  { value: 75, label: "dallas / fort worth" },
  { value: 76, label: "danville" },
  { value: 77, label: "daytona beach" },
  { value: 78, label: "dayton / springfield" },
  { value: 79, label: "decatur, IL" },
  { value: 80, label: "deep east texas" },
  { value: 81, label: "delaware" },
  { value: 82, label: "del rio / eagle pass" },
  { value: 83, label: "denver, CO" },
  { value: 84, label: "des moines, IA" },
  { value: 85, label: "detroit metro" },
  { value: 86, label: "dothan, AL" },
  { value: 87, label: "dubuque" },
  { value: 88, label: "duluth / superior" },
  { value: 89, label: "eastern CO" },
  { value: 90, label: "eastern CT" },
  { value: 91, label: "eastern kentucky" },
  { value: 92, label: "eastern montana" },
  { value: 93, label: "eastern NC" },
  { value: 94, label: "eastern panhandle" },
  { value: 95, label: "eastern shore" },
  { value: 96, label: "east idaho" },
  { value: 97, label: "east oregon" },
  { value: 98, label: "eau claire, WI" },
  { value: 99, label: "elko, NV" },
  { value: 100, label: "elmira-corning" },
  { value: 101, label: "el paso, TX" },
  { value: 102, label: "erie, PA" },
  { value: 103, label: "eugene, OR" },
  { value: 104, label: "evansville, IN" },
  { value: 105, label: "fairbanks, AK" },
  { value: 106, label: "fargo / moorhead" },
  { value: 107, label: "farmington, NM" },
  { value: 108, label: "fayetteville, AR" },
  { value: 109, label: "fayetteville, NC" },
  { value: 110, label: "finger lakes, NY" },
  { value: 111, label: "flagstaff / sedona" },
  { value: 112, label: "flint, MI" },
  { value: 113, label: "florence / muscle shoals" },
  { value: 114, label: "florence, SC" },
  { value: 115, label: "florida keys" },
  { value: 116, label: "fort collins / north CO" },
  { value: 117, label: "fort dodge, IA" },
  { value: 118, label: "fort smith, AR" },
  { value: 119, label: "fort wayne, IN" },
  { value: 120, label: "frederick, MD" },
  { value: 121, label: "fredericksburg, VA" },
  { value: 122, label: "fresno / madera" },
  { value: 123, label: "ft myers / SW florida" },
  { value: 124, label: "gadsden-anniston" },
  { value: 125, label: "gainesville, FL" },
  { value: 126, label: "galveston, TX" },
  { value: 127, label: "glens falls, NY" },
  { value: 128, label: "gold country" },
  { value: 129, label: "grand forks" },
  { value: 130, label: "grand island, NE" },
  { value: 131, label: "grand rapids, MI" },
  { value: 132, label: "great falls, MT" },
  { value: 133, label: "green bay, WI" },
  { value: 134, label: "greensboro, NC" },
  { value: 135, label: "greenville / upstate" },
  { value: 136, label: "gulfport / biloxi" },
  { value: 137, label: "hanford-corcoran" },
  { value: 138, label: "harrisburg, PA" },
  { value: 139, label: "harrisonburg, VA" },
  { value: 140, label: "hartford, CT" },
  { value: 141, label: "hattiesburg, MS" },
  { value: 142, label: "hawaii" },
  { value: 143, label: "heartland florida" },
  { value: 144, label: "helena, MT" },
  { value: 145, label: "hickory / lenoir" },
  { value: 146, label: "high rockies" },
  { value: 147, label: "hilton head" },
  { value: 148, label: "holland, MI" },
  { value: 149, label: "houma, LA" },
  { value: 150, label: "houston, TX" },
  { value: 151, label: "hudson valley, NY" },
  { value: 152, label: "humboldt county" },
  { value: 153, label: "huntington-ashland" },
  { value: 154, label: "huntsville / decatur" },
  { value: 155, label: "imperial county" },
  { value: 156, label: "indianapolis" },
  { value: 157, label: "inland empire, CA" },
  { value: 158, label: "iowa city, IA" },
  { value: 159, label: "ithaca, NY" },
  { value: 160, label: "jackson, MI" },
  { value: 161, label: "jackson, MS" },
  { value: 162, label: "jackson, TN" },
  { value: 163, label: "jacksonville, FL" },
  { value: 164, label: "jacksonville, NC" },
  { value: 165, label: "janesville, WI" },
  { value: 166, label: "jersey shore" },
  { value: 167, label: "jonesboro, AR" },
  { value: 168, label: "joplin, MO" },
  { value: 169, label: "kalamazoo, MI" },
  { value: 170, label: "kalispell, MT" },
  { value: 171, label: "kansas city, MO" },
  { value: 172, label: "kenai peninsula" },
  { value: 173, label: "kennewick-pasco-richland" },
  { value: 174, label: "kenosha-racine" },
  { value: 175, label: "killeen / temple / ft hood" },
  { value: 176, label: "kirksville, MO" },
  { value: 177, label: "klamath falls, OR" },
  { value: 178, label: "knoxville, TN" },
  { value: 179, label: "kokomo, IN" },
  { value: 180, label: "la crosse, WI" },
  { value: 181, label: "lafayette, LA" },
  { value: 182, label: "lafayette / west lafayette" },
  { value: 183, label: "lake charles, LA" },
  { value: 184, label: "lakeland, FL" },
  { value: 185, label: "lake of the ozarks" },
  { value: 186, label: "lancaster, PA" },
  { value: 187, label: "lansing, MI" },
  { value: 188, label: "laredo, TX" },
  { value: 189, label: "la salle co" },
  { value: 190, label: "las cruces, NM" },
  { value: 191, label: "las vegas" },
  { value: 192, label: "lawrence, KS" },
  { value: 193, label: "lawton, OK" },
  { value: 194, label: "lehigh valley" },
  { value: 195, label: "lewiston / clarkston" },
  { value: 196, label: "lexington, KY" },
  { value: 197, label: "lima / findlay" },
  { value: 198, label: "lincoln, NE" },
  { value: 199, label: "little rock" },
  { value: 200, label: "logan, UT" },
  { value: 201, label: "long island, NY" },
  { value: 202, label: "los angeles" },
  { value: 203, label: "louisville, KY" },
  { value: 204, label: "lubbock, TX" },
  { value: 205, label: "lynchburg, VA" },
  { value: 206, label: "macon / warner robins" },
  { value: 207, label: "madison, WI" },
  { value: 208, label: "maine" },
  { value: 209, label: "manhattan, KS" },
  { value: 210, label: "mankato, MN" },
  { value: 211, label: "mansfield, OH" },
  { value: 212, label: "mason city, IA" },
  { value: 213, label: "mattoon-charleston" },
  { value: 214, label: "mcallen / edinburg" },
  { value: 215, label: "meadville, PA" },
  { value: 216, label: "medford-ashland" },
  { value: 217, label: "memphis, TN" },
  { value: 218, label: "mendocino county" },
  { value: 219, label: "merced, CA" },
  { value: 220, label: "meridian, MS" },
  { value: 221, label: "milwaukee, WI" },
  { value: 222, label: "minneapolis / st paul" },
  { value: 223, label: "missoula, MT" },
  { value: 224, label: "mobile, AL" },
  { value: 225, label: "modesto, CA" },
  { value: 226, label: "mohave county" },
  { value: 227, label: "monroe, LA" },
  { value: 228, label: "monroe, MI" },
  { value: 229, label: "monterey bay" },
  { value: 230, label: "montgomery, AL" },
  { value: 231, label: "morgantown, WV" },
  { value: 232, label: "moses lake, WA" },
  { value: 233, label: "muncie / anderson" },
  { value: 234, label: "muskegon, MI" },
  { value: 235, label: "myrtle beach, SC" },
  { value: 236, label: "nashville, TN" },
  { value: 237, label: "new hampshire" },
  { value: 238, label: "new haven, CT" },
  { value: 239, label: "new orleans" },
  { value: 240, label: "new river valley" },
  { value: 241, label: "new york city" },
  { value: 242, label: "norfolk / hampton roads" },
  { value: 243, label: "north central FL" },
  { value: 244, label: "north dakota" },
  { value: 245, label: "northeast SD" },
  { value: 246, label: "northern michigan" },
  { value: 247, label: "northern panhandle" },
  { value: 248, label: "northern WI" },
  { value: 249, label: "north jersey" },
  { value: 250, label: "north mississippi" },
  { value: 251, label: "north platte, NE" },
  { value: 252, label: "northwest CT" },
  { value: 253, label: "northwest GA" },
  { value: 254, label: "northwest KS" },
  { value: 255, label: "northwest OK" },
  { value: 256, label: "ocala, FL" },
  { value: 257, label: "odessa / midland" },
  { value: 258, label: "ogden-clearfield" },
  { value: 259, label: "okaloosa / walton" },
  { value: 260, label: "oklahoma city" },
  { value: 261, label: "olympic peninsula" },
  { value: 262, label: "omaha / council bluffs" },
  { value: 263, label: "oneonta, NY" },
  { value: 264, label: "orange county, CA" },
  { value: 265, label: "oregon coast" },
  { value: 266, label: "orlando, FL" },
  { value: 267, label: "outer banks" },
  { value: 268, label: "owensboro, KY" },
  { value: 269, label: "palm springs, CA" },
  { value: 270, label: "panama city, FL" },
  { value: 271, label: "parkersburg-marietta" },
  { value: 272, label: "pensacola, FL" },
  { value: 273, label: "peoria, IL" },
  { value: 274, label: "philadelphia" },
  { value: 275, label: "phoenix, AZ" },
  { value: 276, label: "pierre / central SD" },
  { value: 277, label: "pittsburgh, PA" },
  { value: 278, label: "plattsburgh-adirondacks" },
  { value: 279, label: "poconos" },
  { value: 280, label: "port huron, MI" },
  { value: 281, label: "portland, OR" },
  { value: 282, label: "potsdam-canton-massena" },
  { value: 283, label: "prescott, AZ" },
  { value: 284, label: "provo / orem" },
  { value: 285, label: "pueblo, CO" },
  { value: 286, label: "pullman / moscow" },
  { value: 287, label: "quad cities, IA/IL" },
  { value: 288, label: "raleigh / durham / CH" },
  { value: 289, label: "rapid city / west SD" },
  { value: 290, label: "reading, PA" },
  { value: 291, label: "redding, CA" },
  { value: 292, label: "reno / tahoe" },
  { value: 293, label: "rhode island" },
  { value: 294, label: "richmond, IN" },
  { value: 295, label: "richmond, VA" },
  { value: 296, label: "roanoke, VA" },
  { value: 297, label: "rochester, MN" },
  { value: 298, label: "rochester, NY" },
  { value: 299, label: "rockford, IL" },
  { value: 300, label: "roseburg, OR" },
  { value: 301, label: "roswell / carlsbad" },
  { value: 302, label: "sacramento" },
  { value: 303, label: "saginaw-midland-baycity" },
  { value: 304, label: "salem, OR" },
  { value: 305, label: "salina, KS" },
  { value: 306, label: "salt lake city" },
  { value: 307, label: "san angelo, TX" },
  { value: 308, label: "san antonio" },
  { value: 309, label: "san diego" },
  { value: 310, label: "sandusky, OH" },
  { value: 311, label: "san luis obispo" },
  { value: 312, label: "san marcos, TX" },
  { value: 313, label: "santa barbara" },
  { value: 314, label: "santa fe / taos" },
  { value: 315, label: "santa maria, CA" },
  { value: 316, label: "sarasota-bradenton" },
  { value: 317, label: "savannah / hinesville" },
  { value: 318, label: "scottsbluff / panhandle" },
  { value: 319, label: "scranton / wilkes-barre" },
  { value: 320, label: "seattle-tacoma" },
  { value: 321, label: "SF bay area" },
  { value: 322, label: "sheboygan, WI" },
  { value: 323, label: "show low, AZ" },
  { value: 324, label: "shreveport, LA" },
  { value: 325, label: "sierra vista, AZ" },
  { value: 326, label: "sioux city, IA" },
  { value: 327, label: "sioux falls / SE SD" },
  { value: 328, label: "siskiyou county" },
  { value: 329, label: "skagit / island / SJI" },
  { value: 330, label: "south bend / michiana" },
  { value: 331, label: "south coast, MA" },
  { value: 332, label: "south dakota" },
  { value: 333, label: "southeast alaska" },
  { value: 334, label: "southeast IA" },
  { value: 335, label: "southeast KS" },
  { value: 336, label: "southeast missouri" },
  { value: 337, label: "southern illinois" },
  { value: 338, label: "southern maryland" },
  { value: 339, label: "southern WV" },
  { value: 340, label: "south florida" },
  { value: 341, label: "south jersey" },
  { value: 342, label: "southwest KS" },
  { value: 343, label: "southwest michigan" },
  { value: 344, label: "southwest MN" },
  { value: 345, label: "southwest MS" },
  { value: 346, label: "southwest TX" },
  { value: 347, label: "southwest VA" },
  { value: 348, label: "space coast, FL" },
  { value: 349, label: "spokane / coeur d'alene" },
  { value: 350, label: "springfield, IL" },
  { value: 351, label: "springfield, MO" },
  { value: 352, label: "state college, PA" },
  { value: 353, label: "statesboro, GA" },
  { value: 354, label: "st augustine, FL" },
  { value: 355, label: "st cloud, MN" },
  { value: 356, label: "st george, UT" },
  { value: 357, label: "stillwater, OK" },
  { value: 358, label: "st joseph" },
  { value: 359, label: "st louis, MO" },
  { value: 360, label: "stockton, CA" },
  { value: 361, label: "susanville, CA" },
  { value: 362, label: "syracuse, NY" },
  { value: 363, label: "tallahassee" },
  { value: 364, label: "tampa bay area" },
  { value: 365, label: "terre haute, IN" },
  { value: 366, label: "texarkana" },
  { value: 367, label: "texoma" },
  { value: 368, label: "the thumb, MI" },
  { value: 369, label: "toledo, OH" },
  { value: 370, label: "topeka, KS" },
  { value: 371, label: "treasure coast, FL" },
  { value: 372, label: "tri-cities, TN" },
  { value: 373, label: "tucson, AZ" },
  { value: 374, label: "tulsa, OK" },
  { value: 375, label: "tuscaloosa" },
  { value: 376, label: "tuscarawas co" },
  { value: 377, label: "twin falls, ID" },
  { value: 378, label: "twin tiers NY/PA" },
  { value: 379, label: "tyler / east TX" },
  { value: 380, label: "upper peninsula, MI" },
  { value: 381, label: "utica-rome-oneida" },
  { value: 382, label: "valdosta, GA" },
  { value: 383, label: "ventura county" },
  { value: 384, label: "vermont" },
  { value: 385, label: "victoria, TX" },
  { value: 386, label: "visalia-tulare" },
  { value: 387, label: "waco, TX" },
  { value: 388, label: "washington, DC" },
  { value: 389, label: "waterloo / cedar falls" },
  { value: 390, label: "watertown, NY" },
  { value: 391, label: "wausau, WI" },
  { value: 392, label: "wenatchee, WA" },
  { value: 393, label: "western IL" },
  { value: 394, label: "western KY" },
  { value: 395, label: "western maryland" },
  { value: 396, label: "western massachusetts" },
  { value: 397, label: "western slope" },
  { value: 398, label: "west virginia (old)" },
  { value: 399, label: "wichita falls, TX" },
  { value: 400, label: "wichita, KS" },
  { value: 401, label: "williamsport, PA" },
  { value: 402, label: "wilmington, NC" },
  { value: 403, label: "winchester, VA" },
  { value: 404, label: "winston-salem, NC" },
  { value: 405, label: "worcester / central MA" },
  { value: 406, label: "wyoming" },
  { value: 407, label: "yakima, WA" },
  { value: 408, label: "york, PA" },
  { value: 409, label: "youngstown, OH" },
  { value: 410, label: "yuba-sutter, CA" },
  { value: 411, label: "yuma, AZ" },
  { value: 412, label: "zanesville / cambridge" },
];
